clean:
	rm -rf build-lan build-wan node_modules

build-lan:
	npm i && npm run build:lan && npm run lint && npm run format

build-wan:
	npm i && npm run build:wan && npm run lint && npm run format

build-lan-and-wan:
	npm i && npm run build:lan && npm run build:wan && npm run lint && npm run format

