clean:
	rm -rf build-lan build-wan node_modules

build-lan:
	npm i && npm run build:lan && npm run format && npm run lint

build-wan:
	npm i && npm run build:wan && npm run format && npm run lint

build-lan-and-wan:
	npm i && npm run build:lan && npm run build:wan && npm run format && npm run lint

