clean:
	rm -rf node_modules android/build

build-lan:
	npm i && npm run build:lan

build-wan:
	npm i && npm run build:wan

build-lan-and-wan:
	npm i && npm run build:lan && npm run build:wan

build: build-lan
